shell:
  program: "zsh"
  args:
    - -l
    - -c
    - "zellij attach --index 0 || zellij"

window:
  opacity: 0.98
  decorations: 'buttonless'
  startup_mode: 'SimpleFullScreen'
  option_as_alt: 'OnlyLeft'

env:
  TERM: xterm-256color

font:
  normal:
    family: "MesloLGS NF"
  size: 13.0

# Colors (Kanagawa Wave)
# Source: https://github.com/rebelot/kanagawa.nvim
colors:
  primary:
    background: '0x181820' #term window background
    foreground: '0xdcd7ba' #cursor and main text

  normal:
    black:   '0x090618'
    red:     '0xc34043'
    green:   '0x76946a'
    yellow:  '0xc0a36e'
    blue:    '0x7e9cd8'
    magenta: '0x957fb8'
    cyan:    '0x6a9589'
    white:   '0xc8c093'

  bright:
    black:   '0x727169'
    red:     '0xe82424'
    green:   '0x98bb6c'
    yellow:  '0xe6c384'
    blue:    '0x7fb4ca'
    magenta: '0x938aa9'
    cyan:    '0x7aa89f'
    white:   '0xdcd7ba'

  selection:
    background: '0x2d4f67'
    foreground: '0xc8c093'

  indexed_colors:
    - { index: 16, color: '0xffa066' }
    - { index: 17, color: '0xff5d62' }

key_bindings:
  - { key: Left,     mods: Alt,             chars: "\x1bb"                          } # Skip word left
  - { key: Right,    mods: Alt,             chars: "\x1bf"                          } # Skip word right
  - { key: Left,     mods: Command,         chars: "\x1bOH",   mode: AppCursor      } # Home
  - { key: Right,    mods: Command,         chars: "\x1bOF",   mode: AppCursor      } # End
  - { key: Back,     mods: Command,         chars: "\x15"                           } # Delete line
  - { key: Back,     mods: Alt,             chars: "\x1b\x7f"                       } # Delete word
  - { key: F,        mods: Command|Alt,     action: "ToggleSimpleFullscreen"        } 
